### ISSUE TITLE
Add vector support

### ISSUE THREAD

**Issue by ivan-wolf** [detailnet/imagemagick-scripts#3]
- Use high input density before resizing (many vector graphics have small dimensions)

**Comment by curzio-della-santa** [comment]
@ivan-wolf  I've added now as vector graphic formats only "SVG" and "EPS", but for EPS there are much more formats available, maybe should we add EPDF,EPI,EPSF,EPSI

I need some help with testing all formats (branch is available):

extract of formats:

``` sh
identify -list format | grep -i encaps
     EPDF  PDF       rw-   Encapsulated Portable Document Format
      EPI  PS        rw-   Encapsulated PostScript Interchange format
      EPS  PS        rw-   Encapsulated PostScript
     EPS2* PS2       -w-   Level II Encapsulated PostScript
     EPS3* PS3       -w+   Level III Encapsulated PostScript
     EPSF  PS        rw-   Encapsulated PostScript
     EPSI  PS        rw-   Encapsulated PostScript Interchange format
      EPT  EPT       rw-   Encapsulated PostScript with TIFF preview
     EPT2  EPT       rw-   Encapsulated PostScript Level II with TIFF preview
     EPT3  EPT       rw+   Encapsulated PostScript Level III with TIFF preview
```

refer to PR #14

**Comment by ivan-wolf** [comment]
It's very hard to define which file types are vector graphics (and eps can be both!).

Is there a way to identify vector graphics using IM?

**Comment by curzio-della-santa** [comment]
theorically any of 
`identify -verbose image.svg`
 can be used.
I extract now the type, but I'll check if there is something more suitable

**Comment by curzio-della-santa** [comment]
Interesting thread about conversion of vector images 
http://www.imagemagick.org/discourse-server/viewtopic.php?t=26151#p114692

**Comment by curzio-della-santa** [comment]
How do I determine if a pdf is raster or vector?

``` sh
grep -c -i "/image" thisfile.pdf
```

If a /image is found is raster

**Comment by curzio-della-santa** [comment]
list of vector formats:
http://en.wikipedia.org/wiki/Image_file_formats#Vector_formats

decided to set as vector graphic following formats:
MSVG,SVG,SVGZ,AI,EPDF,EPI,EPS,EPSF,EPSI,PCT,PDF,PDFA,PICT,PS
