### ISSUE TITLE
Handle transparency

### ISSUE THREAD

**Issue by ivan-wolf** [detailnet/imagemagick-scripts#5]
- Keep transparency by default (when format supports it).
- Add option to specify background color (for other formats or when transparency should be removed).

**Comment by curzio-della-santa** [comment]
I'm not sure if it should be handled in script or,let the freedom to add additional "convert" arguments from command line. (supported by script already)
![image](https://cloud.githubusercontent.com/assets/7221909/6349919/b19a33fe-bc2f-11e4-92f8-e43c764e13f2.png)

Example, image source:
![diddl_post_schnecke](https://cloud.githubusercontent.com/assets/7221909/6349688/2f394938-bc2d-11e4-9162-36c673606c93.png)

``` sh
./convert_image.sh  -i diddl_post_schnecke.png  -o diddl_out.jpeg
```

![diddl_out](https://cloud.githubusercontent.com/assets/7221909/6349708/6e4c584a-bc2d-11e4-81a2-fcd54710a874.jpeg)

``` sh
./convert_image.sh  -i diddl_post_schnecke.png  -o diddl_out_tan.jpeg -background tan  -alpha remove
```

![diddl_out_tan](https://cloud.githubusercontent.com/assets/7221909/6349717/94e8716e-bc2d-11e4-8942-eb7666f1baac.jpeg)

There are so many combinations possible for alpha channel manipulation (http://www.imagemagick.org/Usage/masking/#alpha, http://www.imagemagick.org/script/command-line-options.php#alpha)
my suggestion is to add bought background and alpha arguments, default background="white", alpha="remove"

@ivan-wolf  please feedback

**Comment by ivan-wolf** [comment]
Agree
